\import Logic
\import Logic.Meta

\func test1 : ∃ = (\Sigma) => idp

\func test2 : ∃ Nat = TruncP Nat => idp

\func test3 : ∃ (x : Nat) (x = 0) = TruncP (\Sigma (x : Nat) (x = 0)) => idp

\func test4 : ∃ {x} (x = 0) = TruncP (\Sigma (x : Nat) (x = 0)) => idp

\func test5 : ∃ {x y} (x = 0) = TruncP (\Sigma (x y : Nat) (x = 0)) => idp

\func test6 : ∃ (x y : Nat) (x = 0) (y = 0) = TruncP (\Sigma (x y : Nat) (x = 0) (y = 0)) => idp
