\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.Solver
\import Algebra.Pointed
\import Arith.Nat
\import Data.List
\import Order.Lattice \hiding (MeetSemilattice)
\import Set

\lemma test1 {M : CMonoid} (x y z w : M)
  : (x * (1 * y)) * ((1 * z) * w) = x * ((y * (z * 1)) * w)
  => equation

\lemma test2 {M : CMonoid} (x y z w : M)
  : (y * (1 * z)) * ((1 * x) * w) = x * ((y * (z * 1)) * w)
  => equation

\open Bounded(MeetSemilattice,top)

\lemma test3 {L : MeetSemilattice} (x y z : L) : (x ∧ y) ∧ ((top ∧ x) ∧ z) = z ∧ ((y ∧ x) ∧ (z ∧ y))
  => equation

\lemma addTest {M : AbMonoid} (x y z w : M)
  : (y + (0 + z)) + ((0 + x) + w) = x + ((y + (z + 0)) + w)
  => equation
