\import Algebra.Meta
\import Algebra.Monoid

\func basicTest (f g : Nat -> Nat) (a b : Nat) (p : a = b) (q : f = g) : f a = g b
  => congruence p q

\func funcComp (f : Nat -> Nat) (p : f (f (f 0)) = 0) (q : f (f (f (f (f 0)))) = 0) : f 0 = 0
  => congruence p q

\func funcCompArgRev (f : Nat -> Nat) (p : f (f (f 0)) = 0) (q : f (f (f (f (f 0)))) = 0) : f 0 = 0
  => congruence q p

\func binop (a b c : Nat) (p : b = c) : a Nat.+ b = a Nat.+ c
  => congruence p

\func monoid {M : Monoid} (a b c d : M) (p : b * c = d) : a * b = a * d
  => congruence (M.*-assoc {a} {b} {c}) p