\import Algebra.Meta
\import Arith.Nat
\import Order.PartialOrder

\func reasoning {P : Poset} {x y z : P} (p : y <= z) (q : x <= y) : x <= z
  => equation {q} {p}

\func reasoning2 {P : Poset} {x y z : P} (p : y <= z) (q : x <= y) : x <= z
  => equation {q} y {p}

\func solve {P : Poset} {x y z : P} (p : y <= z) (q : x <= z) : x <= z
  => equation

\func refl {P : Poset} {x : P} : x <= x
  => equation

\func instanceReasoning {x y z : Nat} (p : y <= z) (q : x <= y) : x <= z
  => equation {q} {p}

\func instanceReasoning2 {x y z : Nat} (p : y <= z) (q : x <= y) : x <= z
  => equation {q} y {p}

\func instanceSolve {x y z : Nat} (p : y <= z) (q : x <= y) : x <= z
  => equation
