\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Ordered
\import Arith.Nat
\import Arith.Int
\import Arith.Rat
\import Logic
\import Order.PartialOrder
\import Order.StrictOrder

\lemma contrTest0 {R : LinearlyOrderedSemiring} {a : R} (p : a < a) : Empty
  => linarith

\lemma contrTest1 {R : LinearlyOrderedSemiring} {a b : R} (p : a < b) (q : b <= a) : Empty
  => linarith

\lemma contrTest2 {R : LinearlyOrderedSemiring} {a b c : R} (p : a < b) (q : b = c) (s : c < a) : Empty
  => linarith

\lemma contrTest3 {R : LinearlyOrderedSemiring} {a b : R} (p : a + b < b) (q : a + b <= a) (s : 0 <= a + b) : Empty
  => linarith

\lemma contrTest4 {a b : Nat} (p : a + b < b) (q : a + b <= a) (s : 0 <= a + b) : Empty
  => linarith

\lemma contrTest5 {R : LinearlyOrderedSemiring} {a b c d : R} (p : 3 * a + 2 * b <= 4 * c) (q : 3 * c + 2 * d < 4 * a) (s : 0 <= a + c) (t : a + c <= b + d) : Empty
  => linarith

\lemma contrTest6 {R : OrderedRing} {a b c : R} (p : a - b <= c) (q : b + c <= a - c) (s : b < a) : Empty
  => linarith

\lemma contrTest7 {R : OrderedRing} {a : R} (p : 0 <= a) (q : 0 < negative a) : Empty
  => linarith

\lemma lessEqTest1 {R : LinearlyOrderedSemiring} {a b c : R} (p : a <= b) (q : b + c <= a) : c <= 0
  => linarith

\lemma lessEqTest2 {R : LinearlyOrderedSemiring} {a b c d : R} (p : a <= b + c) (q : b + 2 * c <= d) : 2 * a <= b + d
  => linarith

\lemma lessEqTest3 {a b c d : Int} (p : a <= b - c) (q : b + c <= d + -1 * a) (r : b <= a + c) : 2 * b <= d
  => linarith

\lemma lessTest1 {R : LinearlyOrderedSemiring} {a b c : R} (p : a < b) (q : b + c <= a + a) : c < a
  => linarith

\lemma lessTest2 {R : LinearlyOrderedSemiring} {a b c d : R} (p : a < b + c) (q : b <= 2 * a) (r : d <= 0) : 3 * d < a + c
  => linarith

\lemma lessTest3 {R : LinearlyOrderedSemiring} {a : R} (p : 0 < a) : a < 7 * a
  => linarith

\lemma lessTest4 {R : LinearlyOrderedSemiring} : 3 < {R} 7
  => linarith

\lemma lessTest5 {R : LinearlyOrderedSemiring} {a b c : R} (p : a < b + 1) (q : 2 * b <= a + c) : a < c + 2
  => linarith

\lemma eqTest1 {R : LinearlyOrderedSemiring} {a b : R} (p : a <= 2 * b) (q : b <= 2 * a) (r : a <= 0) : a = 0
  => linarith

\lemma eqTest2 {R : LinearlyOrderedSemiring} {a b c : R} (p : a <= 2 * b + c) (q : b <= 2 * a + c) (r : 5 * (a + c) <= 0) : a + c = 0
  => linarith

\lemma ratTest1 {a b : Rat} (p : a < b) : a < (a + b) * finv 2
  => linarith

\lemma ratTest2 {a b : Rat} (p : a < b * finv 2) : (negative a + b * -1) * ratio -2 3 < b
  => linarith

\lemma ratTest3 {a b c : Rat} (p : 2 * a < b) (q : a <= 0) : ratio 3 4 * (a - b) * finv (ratio 3 2) < negative a
  => linarith
