\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.Solver
\import Algebra.Semiring
\import Meta
\import Set
\open Ring(intCoef)

\lemma semiringTest1 {R : Semiring} (a b c d : R) : a + b * (c + d) = b * c + a + b * d
  => equation

\lemma semiringTest2 {R : Semiring} (a b c d e : R) : a * ((b + c) * d + e) = a * e + (a * (b + c)) * d
  => equation

\lemma natCoefTest {R : Semiring} (a b c d : R) : a + b * (natCoef 3 * c + d + 2 + 2) + a = natCoef 2 * a + natCoef 3 * b * c + natCoef 4 * b + b * d
  => equation

\lemma zeroTest {R : Semiring} (a : R) : a * natCoef 0 = 0
  => equation

\lemma ringTest {R : Ring} (a b c d : R) : a * ((b + c) * d) - (a * b) * d = a * (c * d)
  => equation

\lemma intCoefTest {R : Ring} (b c d : R) : b * natCoef 2 * c + b * (intCoef 3 * c + d + natCoef 4) + b * intCoef -3 = natCoef 5 * b * c + b * (d + 1)
  => equation

\lemma zeroTest2 {R : Ring} (a b c d : R) : a + a * -1 = 0
  => equation
