\import Algebra.Group
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Semiring
\import Paths.Meta

\func test1 {M : Monoid} (x : M) : x = x * ide
  => simplify

\func test2 {M : Monoid} (x : M) : x * x = (x * (ide * x)) * ide
  => simplify

\func test3 {M : Monoid} (x : M) : ide * x * x * ide = x * ide * x * ide * ide
  => simplify

\func test4 {M : AddMonoid} (x : M) : x + x = x + x + zro
  => simplify

\func test5 {R : Semiring} (x : R) : zro = x * zro
  => simplify

\func test6 {R : Ring} (x : R) : negative (x * x) = x * negative x
  => simplify

\func test6' {R : Ring} (x y : R) : x * negative y = negative (x * y)
  => simplify

\func test7 {R : AddGroup} (x : R) : negative (negative x) = x
  => simplify

\func test8 {R : Ring} (x : R) : x * negative ide = negative x
  => simplify

\func test10 {M : Monoid} (x y : M) (p : x * x = y) : x * (1 * x) = y * 1
  => simplify p
