\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Meta
\import Paths

\lemma test1 {M : Monoid} (x y : M) (p : Nat -> x * y = ide)
  : (x * x) * (y * y) = ide
  => using (p 0) solve

\lemma test2 {M : Monoid} (x y : M) (p : x * y = ide)
  => fails {(x * x) * (y * y) = ide} hiding p solve

\lemma test3 {M : Monoid} (x y z : M) (p : x * y = ide) (q : y * z = ide) : x = z
  => equation {hiding p} (x * y * z)

\lemma test3a {M : Monoid} (x y z : M) (p : x * z = x) (q : z * z = y) (s : x * y = y) : x = y
  => equation (x * z * z) {hiding p}

\lemma test4 {M : Monoid} (x y : M) (p : Nat -> x * y = ide)
  : (x * x) * (y * y) = ide
  => equation {using (p 0)}
