\import Logic
\import PropLogic

\func Reflexive {X : \Type} (R : X -> X -> \Type) =>
  \Pi (x : X) -> R x x

\func Symmetric {X : \Type} (R : X -> X -> \Type) =>
  \Pi (x y : X) -> R x y -> R y x

\func Transitive {X : \Type} (R : X -> X -> \Type) =>
  \Pi (x y z : X) -> R x y -> R y z -> R x z

\import Data.Empty

\data Di (A B : \Type)
  | diyes (a : A) (nb : Not B)
  | dino (na : Not A) (b : B)

\data Tri (A B C : \Type)
  | tri_lt (a : A) (nb : Not B) (nc : Not C)
  | tri_eq (na : Not A) (b : B) (nc : Not C)
  | tri_gt (na : Not A) (nb : Not B) (c : C)

\func ReflexiveP {X : \Type} (R : X -> X -> \Prop) =>
   \Pi (x : X) -> R x x

\func SymmetricP {X : \Type} (R : X -> X -> \Prop) =>
  \Pi (x y : X) -> R x y -> R y x

\func TransitiveP {X : \Type} (R : X -> X -> \Prop) =>
  \Pi (x y z : X) -> R x y -> R y z -> R x z

\func EquivalenceP {X : \Type} (R : X -> X -> \Prop) =>
  \Sigma (ReflexiveP R) (SymmetricP R) (TransitiveP R)

\func EquivRelP (X : \Set) => 
  \Sigma (R : X -> X -> \Prop) (EquivalenceP R)
