\import Meta

\lemma assumptionTest (x y z : Nat) : (assumption {1}, assumption {2}, assumption {3}) = (z,y,x)
  => idp

\lemma assumptionError1 (x y z : Nat)
  => fails {Nat} (assumption {0})

\lemma assumptionError2 (x y z : Nat)
  => fails {Nat} (assumption {4})

\lemma functionTest1 (f : Nat -> Nat) : assumption {1} 3 = f 3
  => idp

\lemma functionTest2 (f : \Pi {n : Nat} -> Nat) : assumption {1} {3} = f {3}
  => idp

\func searchTest1 (y : Nat -> Nat) (z : \Sigma Nat Nat) (x : Nat) : Nat
  => assumption

\func searchTest2 (y : Nat -> Nat) (x : Nat) (z : \Sigma Nat Nat) : Nat
  => assumption

\func searchTest3 (x : Nat) (y : Nat -> Nat) (z : \Sigma Nat Nat) : Nat
  => assumption