\import Function
\import Homotopy.Pointed (Pointed \as Pointed')
\import Homotopy.Suspension \using (north \as north', south \as south')

\func Sphere (n : Nat) => iterr Susp n Sphere0
  \where {
    \data Sphere0 | north0 | south0

    \func north (n : Nat) : Sphere n \elim n
      | 0 => north0
      | suc _ => north'

    \func south (n : Nat) : Sphere n \elim n
      | 0 => south0
      | suc _ => south'

    \func Pointed (n : Nat) => \new Pointed' (Sphere n) (north n)
  }