\import Function
\import Homotopy.Pointed
\import Homotopy.Suspension

\func Sphere (n : Nat) => iterr Susp n Sphere0
  \where {
    \data Sphere0 | north0 | south0

    \func north (n : Nat) : Sphere n \elim n
      | 0 => north0
      | suc _ => Susp.north

    \func south (n : Nat) : Sphere n \elim n
      | 0 => south0
      | suc _ => Susp.south

    \func Pointed (n : Nat) => \new Homotopy.Pointed.Pointed (Sphere n) (north n)
  }