\import Data.Array
\import Data.Bool
\import Meta
\import Reflect.ConcreteExpr
\import Reflect.IO
\import Reflect.IO.Meta

\lemma getArgsTest : runIO getArgs = nil => idp

\lemma getArgsTest2 : runIO getArgs 123 {"abc"} = (numberExpr 123, true) :: (stringExpr "abc", false) :: nil => idp

\lemma getArgsTest3 : runIO (getArgs >>= return) = nil => idp

\lemma getArgsTest4 : runIO (getArgs >>= return) {123} "abc" = (numberExpr 123, false) :: (stringExpr "abc", true) :: nil => idp

\lemma getArgsTest5 : runIO (do {
    a1 <- getArgs,
    a2 <- getArgs,
    return (a1 ++ a2)
  }) 123 = (numberExpr 123, true) :: (numberExpr 123, true) :: nil => idp
