\import Data.Maybe
\import Function
\import Meta
\import Reflect.ConcreteExpr
\import Reflect.Meta

\func test1 : (\let t : Nat => run {
  type <- getExpectedType,
  pushObject "A" type,
  0
} \in popObject "A" id) = just (reflect (Nat \levels () ())) => idp

\func test2 : (\let t => getExpectedType id \in t) = nothing => idp

\func test3 : (\let t : _ => run {
  type <- getExpectedType,
  pushObject "A" type,
  0
} \in typecheck (popObject "A" (maybe holeExpr id))) = Nat => idp
