\import Meta
\import Reflect.Meta

\func pushPopTest {A : \Type} (a : A) : run {
  pushObject ``Nat a,
  popObject ``Nat
} = a => idp

\func pushPeekPopTest {A : \Type} (a : A) : run {
  pushObject ``Nat a,
  x <- peekObject ``Nat,
  y <- popObject ``Nat,
  (x,y)
} = (a,a) => idp

\func pushPopPopTest {A : \Type} (a : A) => fails (run {
  pushObject ``Nat a,
  x <- popObject ``Nat,
  y <- popObject ``Nat,
  (x,y)
})

\func pushPopTest2 {A B : \Type} (a : A) => fails (run {
  pushObject ``Nat a,
  popObject ``Int,
})

\func pushPushObject {A : \Type} (a a' : A) : run {
  pushObject ``Nat a,
  pushObject ``Nat a',
  x <- popObject ``Nat,
  y <- popObject ``Nat,
  (x,y)
} = (a',a) => idp

\func pushPopTest3 {A B : \Type} (a : A) (b : B) : run {
  pushObject ``Nat a,
  pushObject ``Int b,
  x <- popObject ``Nat,
  y <- popObject ``Int,
  (x,y)
} = (a,b) => idp
