\import Meta
\import Reflect.Meta

\func pushPopTest {A : \Type} (a : A) : run {
  pushObject "A" a,
  popObject "A"
} = a => idp

\func pushPeekPopTest {A : \Type} (a : A) : run {
  pushObject "A" a,
  x <- peekObject "A",
  y <- popObject "A",
  (x,y)
} = (a,a) => idp

\func pushPopPopTest {A : \Type} (a : A) => fails (run {
  pushObject "A" a,
  x <- popObject "A",
  y <- popObject "A",
  (x,y)
})

\func pushPopTest2 {A B : \Type} (a : A) => fails (run {
  pushObject "A" a,
  popObject "B",
})

\func pushPushObject {A : \Type} (a a' : A) : run {
  pushObject "A" a,
  pushObject "A" a',
  x <- popObject "A",
  y <- popObject "A",
  (x,y)
} = (a',a) => idp

\func pushPopTest3 {A B : \Type} (a : A) (b : B) : run {
  pushObject "A" a,
  pushObject "B" b,
  x <- popObject "A",
  y <- popObject "B",
  (x,y)
} = (a,b) => idp
