\import Algebra.Domain.Bezout
\import Algebra.Domain.Euclidean
\import Algebra.Group
\import Algebra.Group.Category
\import Algebra.Group.Sub
\import Algebra.Group.Symmetric
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.Category
\import Algebra.Monoid.GCD
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.Category
\import Algebra.Ring.Ideal
\import Algebra.Ring.QuotientProperties
\import Algebra.Ring.RingHom
\import Algebra.Semiring
\import Arith.Fin
\import Arith.Int
\import Arith.Nat
\import Category
\import Equiv
\import Function (isSurj)
\import Logic
\import Logic.Meta
\import Meta
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Category
\import Set.Fin
\import Set.Fin.Pigeonhole
\open IntEuclidean

\func coPrimes (n : Nat) : FinSet => fibreFin {n} (\lam (x : Fin n) => EuclideanSemiringData.gcd x n) 1

\func coPrimes-Inv (n : Nat) : SubSet (FinRing {suc n}) \cowith
  | contains x => ∃ (Monoid.Inv x)

\func intMap-FinRing (n : Nat) (k : Int) : intMap {FinRing {n}} k = k mod suc n \elim k {
  | pos zero => idp
  | pos (suc n1) => unfold func (rewrite natCoefSuc (unfold Fin.fromNat (rewrite (fin_mod_id {n} (_ Nat.mod suc n)) idp)))
  | neg (suc n1) => unfold (unfold (ldiv-finEq (inP (\case (suc n1 Nat.mod suc n : Nat) \as r, idp : suc n1 Nat.mod suc n = {Nat} r \with {
    | zero, P => \new Monoid.LDiv {
      | inv => 1
      | inv-right => unfold (rewrite P idp)
    }
    | suc r, P => \new Monoid.LDiv {
      | inv => 0
      | inv-right => unfold (rewrite (P, IntRing.minus__) idp)
    }
  }))))
}

\func intMap-surj (n : Nat) : isSurj (intMap {FinRing {n}}) => \lam y => inP (y, unfold (helper y)) \where
  \func helper {n : Nat} (k : FinRing {n}) : natCoef {FinRing {n}} k = k \elim n, k
    | n, 0 => natCoefZero
    | n, suc k => rewrite (natCoefSuc {FinRing {n}} k, helper k, mod_+-right) (unfold (fin_mod_id {n} (suc k)))

\func ker-int-Coef (n : Nat) : RingHom.KerC (intMap {FinRing {n}}) = {Ideal IntEuclidean} Ideal.closure1 {IntEuclidean} (suc n) =>
  ext (ext (\lam i => ext
      (\lam (c : intMap i = zro) => \case (modEq-ldiv i 0 n) (rewriteI mod-mod (finEq-modeq {i IntEuclidean.mod pos (suc n)} {0} {n} (rewrite intMap-FinRing in c))) \with {
        | inP (a, p) => inP ((a , ()) :: nil, simplify (rewrite (*-comm {IntRing}, p) linarith))
      },
       \lam c => unfold (rewrite (intMap-FinRing, (rewrite AddGroup.minus_zro in ldiv-modEq i 0 n) (Ideal.closure1_LDiv.1 c)) idp))))

\func Z/nZ=FinRing (n : Nat) : Iso {_} {CFactorRing (Ideal.closure1 {IntEuclidean} (suc n))} {FinRing {n}} =>
  transport (\lam X => Iso {_} {CFactorRing X} {FinRing {n}}) (ker-int-Coef n)
      (transport (\lam X => Iso {_} {_} {X}) (RingHom.Im=CodC (intMap {FinRing {n}})
          (intMap-surj n)) (theoremA_C (intMap {FinRing {n}})))

\func coPrimes-eq (n : Nat) : QEquiv {coPrimes n} {SubSet.struct {coPrimes-Inv n}} \cowith {
  | f (k, p) => \let A0 => {?} \in
    (k, inP (\new Monoid.Inv {
      | inv => {?}
      | inv-left => {?}
      | inv-right => {?}
    }))
  | ret => {?}
  | ret_f => {?}
  | f_sec => {?}
}

\func EulerTotient (n : Nat) : Nat => finCard {coPrimes n}

\func chinese-map {n m : Nat} (x : FinRing {n * m + n + m}) : \Sigma (FinRing {n}) (FinRing {m}) =>
  (Fin.fromNat {n} x, Fin.fromNat {m} x)

\func natSemiring-unit {n : Nat} (p : Monoid.Inv {NatSemiring} n) : n = 1 => \case p \with { | (e, p1, p2) => natUnit p1 }

\func chinese-map-surj (n m : Nat) (p : IsCoprime (suc n) (suc m)) : isSurj (chinese-map {n} {m}) => \lam p0 => \case \elim p0 \with {
    | (r1, r2) => \case BezoutRing.chinese2 {IntDomain} (pos r1) (pos r2) (suc n) (suc m) (\lam z l l1 =>
        \let A0 => natSemiring-unit (p (iabs z) (ldiv_iabs l) (ldiv_iabs l1)) \in \new Monoid.Inv {
          | inv => signum z
          | inv-left => rewrite (*-comm, inv iabs.signum_*, A0) idp
          | inv-right => rewrite (inv iabs.signum_*, A0) idp
        }) \with {
      | inP (r, (p1, A1), (p2, A2)) => inP (intMap r, unfold chinese-map (ext (
        \let
          | B1 => rewrite (fin_mod_id {n} r1, helper) in unfold Fin.fromNat in ldiv-finEq {r mod suc (n Nat.* m Nat.+ n Nat.+ m)} {r1} {n} (inP (\new Monoid.LDiv {
            | inv => p1 - suc m IntDomain.* (r div pos (suc n * suc m))
            | inv-right => rewrite (Ring.ldistr_-, A1, helper, inv (pmap (\lam x => x - r1) (divModProp r (suc n * suc m) (\lam p => \case p)))) equation
          }))
          | B2 => rewrite fin_mod_id in pmap (Fin.fromNat {n}) (mod-inv {suc n} {suc m} (\lam p => \case p) (r mod (suc n Nat.* suc m)))
        \in rewrite (intMap-FinRing, helper) (B2 *> rewrite fin_mod_id B1),
        \let
          | B1 => rewrite (fin_mod_id {m} r2, helper) in unfold Fin.fromNat in ldiv-finEq {r mod suc (n Nat.* m Nat.+ n Nat.+ m)} {r2} {m} (inP (\new Monoid.LDiv {
            | inv => p2 - suc n IntDomain.* (r div pos (suc n * suc m))
            | inv-right => rewrite (Ring.ldistr_-, A2, helper, inv (pmap (\lam x => x - r2) (divModProp r (suc n * suc m) (\lam p => \case p)))) equation
          }))
          | B2 => rewrite (fin_mod_id, *-comm {_} {suc m} {suc n}) in
                            pmap (Fin.fromNat {m}) (mod-inv {suc m} {suc n} (\lam p => \case p) (r mod (suc n Nat.* suc m)))

        \in rewrite (intMap-FinRing, helper) (B2 *> rewrite fin_mod_id B1))))
    }} \where {
  \func helper (n m : Nat) : suc ((n Nat.* m) Nat.+ n Nat.+ m) = suc n NatSemiring.* suc m => equation
}

\func function (n m : Nat) (p : IsCoprime n m) (n>0 : 0 < n) (m>0 : 0 < m) (x : coPrimes (n Nat.* m)) : \Sigma (coPrimes n) (coPrimes m) \elim x
  | (x, p) => \let A0 : EuclideanSemiringData.gcd x (n Nat.* m) = 1 => inv p \in (
    (mod_Fin x n>0, \let
      | Am1 => mod_Fin=mod {x} {_} {n>0}
      | A1 : IsCoprime x (n Nat.* m) => IsCoprime.<=gcd (transport (GCD _ _) A0 (EuclideanSemiringData.gcd-isGCD x (n Nat.* m)))
      | A2 : IsCoprime (mod_Fin x n>0) n => \lam z l l1 => A1 z (rewriteI (Nat.divModProp x n) (Semiring.LDiv_+ (Monoid.LDiv.factor-left l1) (transport (Monoid.LDiv {NatSemiring} _) Am1 l))) (Monoid.LDiv.factor-left l1)
      | A2' => IsCoprime.=>gcd A2
      | A2'' => transport (\lam k => GCD k n ide) Am1 A2'
      | A3 => {?} -- gcd-isUnique {_} {x Nat.mod n} {n} (EuclideanSemiringData.gcd-isGCD _ _) A2''
                    \in
      unfold ({?})), (mod_Fin x m>0, {?}))

-- EuclideanSemiringData.gcd x (n Nat.* m) = 1
-- IsCoprime x (n Nat.* m) = \Pi (z : M) -> LDiv z x -> LDiv z (n Nat.* m) -> Inv z

-- \Pi (z : M) -> LDiv z x -> LDiv z n -> Inv z
-- EuclideanSemiringData.gcd x n = 1