\import Algebra.Domain.Euclidean
\import Algebra.Group
\import Algebra.Group.Category
\import Algebra.Group.Sub
\import Algebra.Group.Symmetric
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.Category
\import Algebra.Monoid.GCD
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.Category
\import Algebra.Ring.Ideal
\import Algebra.Ring.QuotientProperties
\import Algebra.Ring.RingHom
\import Algebra.Ring.Sub
\import Algebra.Semiring
\import Arith.Fin
\import Arith.Int
\import Arith.Nat
\import Category
\import Equiv
\import Function (isSurj)
\import Logic
\import Logic.Meta
\import Meta
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Category
\import Set.Fin
\import Set.Fin.Pigeonhole
\open IntEuclidean

\func coPrimes (n : Nat) : FinSet => fibreFin {n} (\lam (x : Fin n) => EuclideanSemiringData.gcd x n) 1

\func coPrimes-Inv (n : Nat) : SubSet (FinRing {suc n}) \cowith
  | contains x => ∃ (Monoid.Inv x)

{- \func multiples_of_1+ (n : Nat) : Ideal IntDomain \cowith
  | contains x => ∃ (Monoid.LDiv {IntDomain} (suc n) x)
  | contains_zro => inP Semiring.zero-div
  | contains_+ (inP A) (inP B) => inP (Semiring.LDiv_+ A B)
  | ideal-left (inP A) => inP (Monoid.LDiv.factor-right A) -}

\func intMap-FinRing (n : Nat) (k : Int) : intMap {FinRing {n}} k = k IntEuclidean.mod suc n \elim k {
  | pos zero => idp
  | pos (suc n1) => unfold func (rewrite natCoefSuc (unfold Fin.fromNat (rewrite (fin_mod_id {n} (_ Nat.mod suc n)) idp)))
  | neg (suc n1) => unfold (unfold (ldiv-finEq (inP (\case (suc n1 Nat.mod suc n : Nat) \as r, idp : suc n1 Nat.mod suc n = {Nat} r \with {
    | zero, P => \new Monoid.LDiv {
      | inv => 1
      | inv-right => unfold (rewrite P idp)
    }
    | suc r, P => \new Monoid.LDiv {
      | inv => 0
      | inv-right => unfold (rewrite (P, IntRing.minus__) idp)
    }
  }))))
}

\func intMap-surj (n : Nat) : isSurj (intMap {FinRing {n}}) => \lam y => inP (y, unfold (helper y)) \where
  \func helper {n : Nat} (k : FinRing {n}) : natCoef {FinRing {n}} k = k \elim n, k
    | n, 0 => natCoefZero
    | n, suc k => rewrite (natCoefSuc {FinRing {n}} k, helper k, mod_+-right) (unfold (fin_mod_id {n} (suc k)))


\func ker-int-Coef (n : Nat) : RingHom.Ker (intMap {FinRing {n}}) = {Ideal IntEuclidean} Ideal.closure1 {IntEuclidean} (suc n) =>
  ext (ext (\lam i => ext
      (\lam (c : intMap i = zro) => \case (modEq-ldiv i 0 n) (rewriteI mod-mod (finEq-modeq {i IntEuclidean.mod pos (suc n)} {0} {n} (rewrite intMap-FinRing in c))) \with {
        | inP (a, p) => inP ((a , ()) :: nil, simplify (rewrite (*-comm {IntRing}, p) linarith))
      },
       \lam c => unfold (rewrite (intMap-FinRing, (rewrite AddGroup.minus_zro in ldiv-modEq i 0 n) (Ideal.closure1_LDiv.1 c)) idp))))

\func Z/nZ=FinRing2 (n : Nat) : Iso {_} {FactorRing (Ideal.closure1 {IntEuclidean} (suc n))} {FinRing {n}} =>
  \let A0 => unfold in theoremA (intMap {FinRing {n}})
     | A1 : CSubRing.struct {RingHom.ImC (intMap {FinRing {n}})} = {CRing} FinRing {n}
      => RingHom.Im=CodC (intMap {FinRing {n}}) (intMap-surj n) \in
    transport (\lam X => Iso {_} {FactorRing X} {FinRing {n}}) (ker-int-Coef n)
        (transport (\lam X => Iso {_} {_} {X}) A1 {?})

{- \func Z/nZ=FinRing (n : Nat) : QEquiv {FactorRing (multiples_of_1+ n)} {FinRing {n}} \cowith
  | f x => \case \elim x \with {
    | in~ a => IntEuclidean.mod a (suc n)
    | ~-equiv x y r i => ldiv-modEq x y n r @ i
  }
  | ret x => in~ x
  | ret_f x => \case \elim x \with {
    | in~ a => FactorRing.fequiv {multiples_of_1+ n} {pos (a mod pos (suc n) Nat.mod suc n)} {a} (inP (\new Monoid.LDiv {
      | inv => negative (a div suc n)
      | inv-right => rewrite mod-mod (rewriteI {3} (divModProp a (suc n) (\lam p => \case p))
          (rewrite (helper _ (pos (suc n) IntRing.* a div pos (suc n)), Ring.negative_*-right {IntEuclidean} {pos (suc n)}) idp))
    }))
  }
  | f_sec x => rewrite IntEuclidean.natMod=mod (\case \elim x \with {
    | 0 => idp
    | suc x => repeat {2} (rewrite fin_mod_id) idp
  })
  \where {
    \lemma helper (a b : Int) : a - (b + a) = negative b => simplify
  } -}

\func coPrimes-eq (n : Nat) : QEquiv {coPrimes n} {SubSet.struct {coPrimes-Inv n}} \cowith {
  | f (k, p) => \let A0 => {?} \in
    (k, inP (\new Monoid.Inv {
      | inv => {?}
      | inv-left => {?}
      | inv-right => {?}
    }))
  | ret => {?}
  | ret_f => {?}
  | f_sec => {?}
}

\func EulerTotient (n : Nat) : Nat => finCard {coPrimes n}

\func function (n m : Nat) (p : IsCoprime n m) (n>0 : 0 < n) (m>0 : 0 < m) (x : coPrimes (n Nat.* m)) : \Sigma (coPrimes n) (coPrimes m) \elim x
  | (x, p) => \let A0 : EuclideanSemiringData.gcd x (n Nat.* m) = 1 => inv p \in (
    (mod_Fin x n>0, \let
      | Am1 => mod_Fin=mod {x} {_} {n>0}
      | A1 : IsCoprime x (n Nat.* m) => IsCoprime.<=gcd (transport (GCD _ _) A0 (EuclideanSemiringData.gcd-isGCD x (n Nat.* m)))
      | A2 : IsCoprime (mod_Fin x n>0) n => \lam z l l1 => A1 z (rewriteI (Nat.divModProp x n) (Semiring.LDiv_+ (Monoid.LDiv.factor-left l1) (transport (Monoid.LDiv {NatSemiring} _) Am1 l))) (Monoid.LDiv.factor-left l1)
      | A2' => IsCoprime.=>gcd A2
      | A2'' => transport (\lam k => GCD k n ide) Am1 A2'
      | A3 => {?} -- gcd-isUnique {_} {x Nat.mod n} {n} (EuclideanSemiringData.gcd-isGCD _ _) A2''
                    \in
      unfold ({?})), (mod_Fin x m>0, {?}))

-- EuclideanSemiringData.gcd x (n Nat.* m) = 1
-- IsCoprime x (n Nat.* m) = \Pi (z : M) -> LDiv z x -> LDiv z (n Nat.* m) -> Inv z

-- \Pi (z : M) -> LDiv z x -> LDiv z n -> Inv z
-- EuclideanSemiringData.gcd x n = 1