\import Paths.Meta

\func propTest (x y : Nat) (p q : x = y) : p = q => ext

\func funExtTest {A : \Type} (B : A -> \Type) (f g : \Pi (x : A) -> (B x)) (h : \Pi (x : A) -> f x = g x) : f = g
  => ext (\lam a => h a)

\func funExtTest2 {A B C : \Type} (f g : A -> B -> C) (h : \Pi (y : B) (x : A) -> f x y = g x y) : f = g
  => ext (\lam x y => h y x)

\func funExtTest3 {A : \Type} (B : A -> \Type) (C : \Pi (x : A) -> B x -> \Type) (f g : \Pi (x : A) (y : B x) -> C x y) (h : \Pi (x : A) (y : B x) -> f x y = g x y) : f = g
  => ext h
