\import Paths
\import Paths.Meta

\func funTransportTest {A : \Type} (B C : A -> \Type) {a a' : A} (p : a = a') (f : B a -> C a) (g : B a' -> C a') (t : \Pi (b : B a) -> transport C p (f b) = g (transport B p b)) : transport (\lam x => B x -> C x) p f = g
  => simp_coe t

\func funCoeTest {A1 A2 : \Type} (B C : A1 -> A2 -> \Type) {a1 a1' : A1} {a2 a2' : A2} (p1 : a1 = a1') (p2 : a2 = a2') (f : B a1 a2 -> C a1 a2) (g : B a1' a2' -> C a1' a2')
                 (t : \Pi (b : B a1 a2) -> coe (\lam i => C (p1 @ i) (p2 @ i)) (f b) right = g (coe (\lam i => B (p1 @ i) (p2 @ i)) b right)) : coe (\lam i => B (p1 @ i) (p2 @ i) -> C (p1 @ i) (p2 @ i)) f right = g
  => simp_coe t

\func funTransportTest2 {A : \Type} (B1 B2 B3 B4 : A -> \Type) {a a' : A} (p : a = a') (f : (B1 a -> B2 a) -> B3 a -> B4 a) (g : (B1 a' -> B2 a') -> B3 a' -> B4 a')
                        (t : \Pi (h : B1 a' -> B2 a) (y : B3 a) -> transport B4 p (f (\lam x => h (transport B1 p x)) y) = g (\lam x => transport B2 p (h x)) (transport B3 p y)) : transport (\lam x => (B1 x -> B2 x) -> B3 x -> B4 x) p f = g
  => simp_coe t

\func piTransportTest {A B : \Type} (C : B -> A -> \Type) {a a' : A} (p : a = a') (f : \Pi (y : B) -> C y a) (g : \Pi (y : B) -> C y a') (t : \Pi (b : B) -> transport (C b) p (f b) = g b) : transport (\lam x => \Pi (y : B) -> C y x) p f = g
  => {?}

\func piCoeTest {A1 A2 B : \Type} (C : B -> A1 -> A2 -> \Type) {a1 a1' : A1} {a2 a2' : A2} (p1 : a1 = a1') (p2 : a2 = a2') (f : \Pi (y : B) -> C y a1 a2) (j : I) (g : \Pi (y : B) -> C y (p1 @ j) (p2 @ j))
                (t : \Pi (b : B) -> coe (\lam i => C b (p1 @ i) (p2 @ i)) (f b) j = g b) : coe (\lam i => \Pi (y : B) -> C y (p1 @ i) (p2 @ i)) f j = g
  => {?}

\func piTransportArgTest {A B : \Type} (C : B -> A -> \Type) {a a' : A} (p : a = a') (f : \Pi (y : B) -> C y a) (b : B) (c : C b a') (t : transport (C b) p (f b) = c) : transport (\lam x => \Pi (y : B) -> C y x) p f b = c
  => {?}

\func piCoeArgTest {A1 A2 B : \Type} (C : B -> A1 -> A2 -> \Type) {a1 a1' : A1} {a2 a2' : A2} (p1 : a1 = a1') (p2 : a2 = a2') (f : \Pi (y : B) -> C y a1 a2) (b : B) (j : I) (c : C b (p1 @ j) (p2 @ j))
                   (t : coe (\lam i => C b (p1 @ i) (p2 @ i)) (f b) j = c) : coe (\lam i => \Pi (y : B) -> C y (p1 @ i) (p2 @ i)) f j b = c
  => {?}

\func projTransportTest {A B : \Type} (C : B -> A -> \Type) {a a' : A} (p : a = a') (t : \Sigma (b : B) (C b a)) (b : B) (h : t.1 = b) : (transport (\lam x => \Sigma (b : B) (C b x)) p t).1 = b
  => {?}

\func projCoeTest {B : \Type} (C : B -> I -> \Type) (t : \Sigma (b : B) (C b left)) (b : B) (h : t.1 = b) (j : I) : (coe (\lam i => \Sigma (b : B) (C b i)) t j).1 = b
  => {?}

\func projTransportTest2 {A : \Type} (B C : A -> \Type) {a a' : A} (p : a = a') (t : \Sigma (B a) (C a)) (c : C a') (h : transport C p t.2 = c) : (transport (\lam x => \Sigma (B x) (C x)) p t).2 = c
  => {?}

\func projCoeTest2 (B C : I -> \Type) (t : \Sigma (B left) (C left)) (j : I) (c : C j) (h : coe C t.2 j = c) : (coe (\lam i => \Sigma (B i) (C i)) t j).2 = c
  => {?}

\func tupleTransportTest {A : \Type} (B C : A -> \Type) (D : \Pi (x : A) -> B x -> C x -> \Prop) {a a' : A} (p : a = a') (t : \Sigma (b : B a) (c : C a) (D a b c)) (s : \Sigma (b : B a') (c : C a') (D a' b c))
                         (h1 : transport B p t.1 = s.1) (h2 : transport C p t.2 = s.2) : transport (\lam x => \Sigma (b : B x) (c : C x) (D x b c)) p t = s
  => {?}

\func tupleCoeTest {A : \Type} (B C : I -> \Type) (D : \Pi (i : I) -> B i -> C i -> \Prop) (t : \Sigma (b : B left) (c : C left) (D left b c)) (j : I) (s : \Sigma (b : B j) (c : C j) (D j b c))
                   (h1 : coe B t.1 j = s.1) (h2 : coe C t.2 j = s.2) : coe (\lam i => \Sigma (b : B i) (c : C i) (D i b c)) t j = s
  => {?}

\func fieldTransportTest {A : \Type} (B C : A -> \Type) {a a' : A} (p : a = a') (r : R B C a) (c : C a') (h : transport C p r.c = c) : R.c {transport (R B C) p r} = c
  => {?}
  \where {
    \record R {A : \Type} (B C : A -> \Type) (a : A) (b : B a) (c : C a)
  }

\func fieldCoeTest (B C : I -> \Type) (r : R B C left) (j : I) (c : C j) (h : coe C r.c j = c) : R.c {coe (R B C) r j} = c
  => {?}
  \where {
    \record R (B C : I -> \Type) (j : I) (b : B j) (c : C j)
  }

\func recordTransportTest {A : \Type} (B C : A -> \Type) {a a' : A} (p : a = a') (r : R B C a) (r' : R B C a') (h1 : transport B p r.b = r'.b) (h2 : transport C p r.c = r'.c) : transport (R B C) p r = r'
  => {?}
  \where {
    \record R {A : \Type} (B C : A -> \Type) (a : A) (b : B a) (c : C a)
  }

\func recordCoeTest (B C : I -> \Type) (r : R B C left) (j : I) (r' : R B C j) (h1 : coe B r.b j = r'.b) (h2 : coe C r.c j = r'.c) : coe (R B C) r j = r'
  => {?}
  \where {
    \record R (B C : I -> \Type) (j : I) (b : B j) (c : C j)
  }

\func pathTransportTest {A B : \Type} (f g : A -> B) {a a' : A} (p : a = a') (q : f a = g a) (s : f a' = g a') (h : q *> pmap g p = pmap f p *> s) : transport (\lam x => f x = g x) p q = s
  => simp_coe h

\func pathTransportTest2 {A B : \Type} (b : B) (g : A -> B) {a a' : A} (p : a = a') (q : b = g a) (s : b = g a') (h : q *> pmap g p = s) : transport (\lam x => b = g x) p q = s
  => simp_coe h

\func pathCoeTest {B : \Type} (f g : I -> B) (q : f left = g left) (s : f right = g right) (h : q *> path g = path f *> s) : coe (\lam i => f i = g i) q right = s
  => simp_coe h

\func pathCoeTest2 {B : \Type} (b : B) (g : I -> B) (q : b = g left) (s : b = g right) (h : q *> path g = s) : coe (\lam i => b = g i) q right = s
  => simp_coe h
