\import Algebra.Group.Sub
\import Algebra.Monoid
\import Algebra.Ring
\import Algebra.Semiring.Sub
\import Paths.Meta

\class SubRing \extends SubSemiring, SubAddGroup {
  \override S : Ring

  \func struct : Ring \cowith
    | Semiring => SubSemiring.struct
    | AbGroup => SubAddGroup.abStruct \this
} \where {
  \func cStruct {R : CRing} (S : SubRing R) : CRing \cowith
    | Ring => S.struct
    | *-comm => ext *-comm
}