\import Algebra.Group
\import Algebra.Group.Aut
\import Algebra.Group.Category
\import Algebra.Monoid
\import Algebra.Monoid.Category
\import Category

\class MonoidCatAction {C : Precat} (M : Monoid) (\classifying  c : C){
  | act : MonoidHom M (End c)
}

\instance DeloopM (M : Monoid) : Precat
  | Ob => \Sigma
  | Hom _ _ => M
  | id _ => M.ide
  | o => M.*
  | id-left => M.ide-left
  | id-right => M.ide-right
  | o-assoc => M.*-assoc
