\import Algebra.Group
\import Algebra.Monoid
\import Algebra.Monoid.Category
\import Category (Cat)
\import Category.Sub
\import Equiv
\import Paths

\instance GroupCategory : Cat Group
  => subCat (\new Embedding {
    | f (G : Group) => \new Monoid G.E G.ide (G.*) G.ide-left G.ide-right G.*-assoc
    | isEmb G H => \new Retraction {
      | sec => Group.equals G H
      | f_sec => idpe
    }
  })
