\import Algebra.Group
\import Algebra.Group.Category
\import Algebra.Group.Sub
\import Algebra.Monoid
\import Algebra.Monoid.Category
\import Algebra.Monoid.Sub
\import Algebra.Pointed
\import Category
\import Function \hiding (id, o)
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set.Category
\open Group

\func \infix 7 // (G : Group) (H : NormalSubGroup G) : Group => H.Quotient

{- | properties needed from a commutative triangle $$X \to Y \to Z$$ in the category of groups -}
\class GroupTriangle \noclassifying (X Y Z : Group) (f : GroupHom X Y) (g : GroupHom Y Z) (h : GroupHom X Z) (comm : h = g GroupCat.∘ f) {
  \lemma surjectivity-2-out-3  (p : isSurj h) (q : isSurj f) : isSurj g => \lam (z : Z) => surjectivity-2-out-3-pw p q z

  \lemma surjectivity-2-out-3-pw  (p : isSurj h) (q : isSurj f) (z : Z): ∃ (y : Y) (g y = z) =>
    \case p z \with {
      | inP a => inP (f a.1, g (f a.1) ==< helper >== h a.1 ==<  a.2 >== z `qed)
    }
    \where \lemma helper {a : X} : g (f a) = h a =>
      g (f a)             ==< idp >==
      (g GroupCat.∘ f) a  ==< pmap (\lam (e : GroupHom X Z) => e a) (inv comm) >==
      h a `qed
}

\class QuotientUnivProperty \noclassifying (G H : Group) (f : GroupHom G H) (N : NormalSubGroup G) (p : N SubGroupMeetSemilattice.<= f.Ker) {
  \func univ (a : G // N) : f.Im.struct \elim a
    | in~ n => (f n, inP (n, idp))
    | ~-equiv y x r => ext (equality-check (rewriteI (f.func-inverse, f.func-*) (p (inverse y * x) r)))

  \lemma univ-* (x y : G // N) : univ (x N.Quotient.* y) = univ x f.Im.struct.* univ y \elim x, y
    | in~ _, in~ _ => ext (unfold (SubSemigroup.struct.*) f.func-*)

  \func univ_img : GroupHom (G // N) f.Im.struct \cowith
    | func => univ
    | func-* => rewrite univ-* idp

  \func univ_map_surj : isSurj univ => \lam g => \case \elim g \with {
    | (y, inP x) => inP (in~ x.1, ext x.2)
  }

  \func univ_hom : GroupHom (G // N) H \cowith
    | func x => f.im.func (univ x)
    | func-* => rewrite (univ-*, f.im.func-*) idp \where {
  }

  \lemma universalProperty : univ_hom GroupCat.∘ quotient-map = f =>
    exts (\lam (x : G) => (univ_hom GroupCat.∘ quotient-map) x ==< idp >==
    univ_hom (quotient-map x) ==< idp >==
    univ_hom (in~ x) ==< idp >== f x `qed)
}

\class TheoremA \extends QuotientUnivProperty {
  | N => f.Ker
  | p => SubGroupMeetSemilattice.<=-refl

  \func statement : GroupHom.IsIsomorphism {univ_img} =>
    (\lam {a a' : SubGroup.Cosets {f.Ker}} p => \case \elim a, \elim a', p \with {
      | in~ b1, in~ b2, p2 => ~-equiv {G} b1 b2 (GroupHom.same-images-test (pmap (\lam x => x.1) p2))
    }, univ_map_surj)
}
{- | The quotient groups $SN/N$ and $S/(S \cap N)$ are isomorphic.-}
\class TheoremB (G : Group) (S : SubGroup G) (N : NormalSubGroup G) {
     \func f : GroupHom => (NormalSubGroup.quotient {FrobeniusProductN.N<=SN S N}) ∘ (SubGroup.embed {FrobeniusProductN.S<=SN S N})

     --\func Kerf=S-cap-N : GroupHom.Ker {f} = S ∩1 N
}

{- | Now we apply all of these universal properties to the case when $N = \ker f$ and we get the first isomorphism theorem in the end-}
\class FirstIsomorphismTheorem \noclassifying (G : Group) (H : Group) (f : GroupHom G H) {
  \func UniversalProperty : QuotientUnivProperty G H f f.Ker SubGroupMeetSemilattice.<=-refl \cowith

  \func univ : GroupHom (G // f.Ker) H => UniversalProperty.univ_hom

  \func quot : GroupHom G (G // f.Ker) => quotient-map

  \func Triangle : GroupTriangle \cowith
    | X => G
    | Y => G // f.Ker
    | Z => H
    | f => quot
    | g => univ
    | h => f
    | comm => UniversalProperty.universalProperty

  \lemma universalKerProp : univ GroupCat.∘ quot = f => UniversalProperty.universalProperty

  \lemma universalQuotientKernel (g : G // f.Ker) (q : univ g = ide) : g = f.Ker.Quotient.ide =>
    \case g \as b, idp : g = b \return b = f.Ker.Quotient.ide \with {
      | in~ a, p => inv (f.Ker.criterionForKernel a (universalQuotientKernel' a (transport (\lam z => univ z = ide) p q))
      )
    } \where {
      \lemma helper-1 (a : G) (q : univ (in~ a) = ide) : in~ a = f.Ker.Quotient.ide =>
        inv (f.Ker.criterionForKernel a (universalQuotientKernel' a q))
    }

  \lemma evidTrivKer : univ.TrivialKernel =>
    \lam {g : G // f.Ker} (p : univ.Ker.contains g) => universalQuotientKernel g p

  \lemma universalQuotientKernel' (a : G) (q : univ (in~ a) = ide) : f.Ker.contains a =>
    f a ==< inv (technical-helper a) >==
    univ (in~ a) ==< q >==
    ide `qed
    \where \lemma technical-helper  (a : G) : univ (in~ a) = f a =>
      univ (in~ a) ==< pmap univ {in~ a} {quot a} idp >==
      univ (quot a) ==< idp >==
      (univ GroupCat.∘ quot) a ==< pmap (\lam (z : GroupHom G H) => z a) universalKerProp >==
      f a `qed

  \lemma univKer-mono : isInj univ.func => univ.Kernel-injectivity-test evidTrivKer

  \lemma univKer-epi (p : isSurj f): isSurj univ => Triangle.surjectivity-2-out-3 p (NormalSubGroup.quotient.surj {f.Ker})

  \lemma FirstIsoTheorem (p : isSurj f) : univ.IsIsomorphism => (univKer-mono, univKer-epi p)
}

-- application of first Isomorphism theorem without need to define local instances

\func GroupFirstIsoCorollary-setwise {G H : Group} {N : NormalSubGroup G} (f : GroupHom G H) (p : N = f.Ker) (q : isSurj f):
  \Sigma(h : GroupHom (G // N) H) h.IsIsomorphism =>
  transport {NormalSubGroup G} (\lam X => \Sigma (f : GroupHom (G // X) H) f.IsIsomorphism) (inv p) (GroupFirstIsoCorollary-24 f q)
  \where{
    \func GroupFirstIsoCorollary-2 {G H : Group} (f : GroupHom G H) :
      GroupHom (G // f.Ker) H => FirstIsomorphismTheorem.univ {\new FirstIsomorphismTheorem {
                                                                    | G => G | H => H | f => f
                                                                  }}

    \func GroupFirstIsoCorollary-24 {G H : Group} (f : GroupHom G H) (q : isSurj f) :
      \Sigma (a : GroupHom (G // f.Ker) H) a.IsIsomorphism => (GroupFirstIsoCorollary-2 f,
                                                                  FirstIsomorphismTheorem.FirstIsoTheorem {\new FirstIsomorphismTheorem {
                                                                                                             | G => G | H => H | f => f
                                                                                                           }} q)

    \func GroupFirstIsoCorollary-3 {G H : Group} {N : NormalSubGroup G} (f : GroupHom G H) (p : N = f.Ker) :
      GroupHom (G // N) H =>
      transport {NormalSubGroup G} (\lam X => GroupHom (G // X) H) (inv p) (GroupFirstIsoCorollary-2 f)
  }

\func GroupFirstIsoCorollary {G H : Group} {N : NormalSubGroup G} (f : GroupHom G H) (p : N = f.Ker) (q : isSurj f):
  \Sigma (f : GroupHom (G // N) H) (Iso {GroupCat} {G // N} {H} f) => ((GroupFirstIsoCorollary-setwise f p q).1,
                                                                       (GroupCat.Iso<->Inj+Surj (GroupFirstIsoCorollary-setwise f p q).1).2
                                                                           (GroupFirstIsoCorollary-setwise f p q).2)
