\import Category
\import Category.Meta
\import Paths.Meta
\import Topology.TopSpace

\instance TopCat : Cat TopSpace
  | Hom => ContMap
  | id X => \new ContMap {
    | func x => x
    | func-cont t => t
  }
  | o g f => \new ContMap {
    | func x => g (f x)
    | func-cont t => func-cont {f} (func-cont {g} t)
  }
  | id-left => idp
  | id-right => idp
  | o-assoc => idp
  | univalence => sip (\lam {X} {S1} {S2} h1 h2 => exts (\lam U => ext (func-cont {h2} {U}, func-cont {h1} {U})))
