\import Algebra.Ordered
\import Algebra.Ring.Localization
\import Algebra.Ring.Localization.Field
\import Arith.Int
\import Paths

\record Rat (extract : LocRing.Type (localization-isOrderedField.positiveSubset IntRing))

\instance RatField : DiscreteOrderedField Rat
  => transport (\lam X => DiscreteOrderedField X)
               (path (iso {LocRing.Type (localization-isOrderedField.positiveSubset IntRing)} {Rat} (\lam x => \new Rat x) (\lam r => Rat.extract {r}) idpe idpe))
               (localization-isDiscreteOrderedField IntRing)
