\import Logic
\import Paths

\data Bool | true | false

\data So (b : Bool) \with
  | true => so
  \where
    \func absurd {A : \Type} (s : So false) : A

\func not (b : Bool) : Bool
  | true => false
  | false => true

\func if {A : \Type} (b : Bool) (then else : A) : A \elim b
  | true => then
  | false => else

\func and (x y : Bool) : Bool => if x y false

\func or (x y : Bool) : Bool => if x true y

\lemma true/=false (p : true = false) : Empty => So.absurd (transport So p so)